### ISSUE TITLE
Nowa funkcjonalność

### ISSUE THREAD

**Issue by bibiak1** [freedns/freedns#12]
Czy mogę prosić o dodanie do xmlrpc.php obsługi update'ów na obiektach TXT?
Potrzebne to jest do potwierdzeń certyfikatów wildcard z letsencrypt

**Comment by bibiak1** [comment]
Da się coś z tym zrobić?

**Comment by blapud** [comment]
Podpinam się pod wątek. Może ktoś zna jakiś workaround/rozwiązanie? Chyba nie można się spodziewać szybkich zmian w projekcie patrząc na newsy z 42.pl ;]

**Comment by bibiak1** [comment]
Napisałem skrypt, który to robi poprzez web - https://github.com/bibiak1/freedns-txt

**Comment by pkonopelko** [comment]
+1
